apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netdata
  namespace: monitoring
  labels:
    app: netdata
spec:
  selector:
    matchLabels:
      app: netdata
  template:
    metadata:
      labels:
        app: netdata
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: netdata
      containers:
      - name: netdata
        image: netdata/netdata
        imagePullPolicy: Always
        ports:
        - containerPort: 19999
          hostPort: 19999
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
            - SYS_ADMIN
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: root
          mountPath: /host/root
          readOnly: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: root
        hostPath:
          path: /

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: netdata
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netdata
rules:
- apiGroups: [""]
  resources: ["services", "events", "endpoints", "pods", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netdata
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netdata
subjects:
- kind: ServiceAccount
  name: netdata
  namespace: monitoring

---
apiVersion: v1
kind: Service
metadata:
  name: netdata
  namespace: monitoring
  labels:
    app: netdata
spec:
  type: NodePort
  ports:
  - port: 19999
    targetPort: 19999
    nodePort: 30099
  selector:
    app: netdata