apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-depl
  annotations:
    netdata.io/enabled: "true"  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes
  template:
    metadata:
      labels:
        app: quotes
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      initContainers:
      - name: otel-agent-installer
        image: busybox
        command: ['sh', '-c', 'wget -O /otel-agent/opentelemetry-python-agent.whl https://github.com/open-telemetry/opentelemetry-python-contrib/releases/latest/download/opentelemetry_instrumentation-*.whl']
        volumeMounts:
        - name: otel-agent
          mountPath: /otel-agent
      containers:
        - name: quotes
          image: mariamghamgui/quotes:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.name=quotes-service
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://otel-collector:4318"
          - name: PYTHONPATH
            value: "/otel-agent:${PYTHONPATH}"
          volumeMounts:
          - name: otel-agent
            mountPath: /otel-agent
          ports:
          - containerPort: 5000
      volumes:
      - name: otel-agent
        emptyDir: {}

--- 
apiVersion: v1
kind: Service
metadata:
  name: quotes-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: quotes
  ports:
    - name: quotes
      protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: quotes-nodeport-srv
spec:
  type: NodePort
  selector:
    app: quotes
  ports:
    - name: quotes
      port: 5000
      targetPort: 5000  
      protocol: TCP
